### ISSUE TITLE
log4j와 slf4j를 혼합하여 사용하는 건가요?

### ISSUE THREAD

**Issue by bestheroz** [mabaji/springFrameworkTest#1]
https://github.com/mabaji/springFrameworkTest/blob/12078d62b1bf3b330ef92d95b8c795294c65a5af/pom.xml#L78

**Comment by mabaji** [comment]
아무래도 익숙하니 넣은 것 같아요.
코드의 유연성을 위해 어떤 것을 사용하면 좋을지에 대한 고민은 해봐야겠네요 ^^
